// apps/unicorns-admin/src/app/app.component.ts
import {Component} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {IProduct} from "@nx-monorepo/unicorns/util-interfaces";

@Component({
  selector: 'nx-monorepo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  products: IProduct[] = [
    {
      "id": 1,
      "name": "List 1",
      "image": "https://source.unsplash.com/1600x900/?cat",
      "description": "This is item #1",
      "price": 100
    },
    {
      "id": 2,
      "name": "List 2",
      "image": "https://source.unsplash.com/1600x900/?dog",
      "description": "This is item #2",
      "price": 200
    },
    {
      "id": 3,
      "name": "List 3",
      "image": "https://source.unsplash.com/1600x900/?bird",
      "description": "This is item #3",
      "price": 300
    },
    {
      "id": 4,
      "name": "Test",
      "image": "https://source.unsplash.com/1600x900/?home",
      "description": "This is item #4",
      "price": 400
    }
  ];

  constructor(private http: HttpClient) {
    // this.http.get<IProduct[]>('http://localhost:3001/products').subscribe((products) => {
    //   this.products = products;
    // });
  }

}

<nx-monorepo-header></nx-monorepo-header>
<div class="main" >
  <mat-card class="example-card" *ngFor="let product of products">
    <img mat-card-image style="height: 200px" src="{{product.image}}" alt="{{product.name}}">
    <mat-card-content>
      <p>
        The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan.
        A small.
      </p>
    </mat-card-content>
    <mat-card-actions style="color: dodgerblue">
      <button mat-button>SHARE</button>
      <button mat-button>LEARN MORE</button>
    </mat-card-actions>
  </mat-card>
</div>

<router-outlet></router-outlet>

// apps/unicorns-main/src/app/app.tsx
import styles from './app.module.css';
import {Button, Card, CardContent, CardMedia, Typography} from "@mui/material";
import {useEffect, useState} from "react";
import {Header} from "@nx-monorepo/unicorns/ui-shared-react";
import {IProduct} from "@nx-monorepo/unicorns/util-interfaces";


export function App() {
  const [products, setProducts] = useState<IProduct[]>([
    {
      "id": 1,
      "name": "List 1",
      "image": "https://source.unsplash.com/1600x900/?cat",
      "description": "This is item #1",
      "price": 100
    },
    {
      "id": 2,
      "name": "List 2",
      "image": "https://source.unsplash.com/1600x900/?dog",
      "description": "This is item #2",
      "price": 200
    },
    {
      "id": 3,
      "name": "List 3",
      "image": "https://source.unsplash.com/1600x900/?bird",
      "description": "This is item #3",
      "price": 300
    },
    {
      "id": 4,
      "name": "Test",
      "image": "https://source.unsplash.com/1600x900/?home",
      "description": "This is item #4",
      "price": 400
    }
  ]);
  const getProducts = async () => {
    const res = await fetch('http://localhost:3001/products');
    const data: IProduct[] = await res.json();
    if (!res.ok) {
      throw new Error('Something went wrong!');
    }
    setProducts(data);
  }

  // useEffect(() => {
  //   getProducts();
  // }, []);

  return (
    <>
      <Header/>
      <div className={styles['main']}>
        {products.map((product: IProduct) => (
          <Card sx={{maxWidth: 345}}>
            <CardMedia
              component="img"
              height="140"
              image={product.image}
              alt="green iguana"
            />
            <CardContent>
              <Typography variant="body2" color="text.secondary">
                Lizards are a widespread group of squamate reptiles, with over 6,000
                species, ranging across all continents except Antarctica
              </Typography>
            </CardContent>
            <Button size="small">Share</Button>
            <Button size="small">Learn More</Button>
          </Card>
        ))}
      </div>
    </>
  );
}

export default App;
